### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by alfonsojon** [canyonmodded/canyon#48]
Cannot download from Jenkins, building from source fails

```[ERROR] Failed to execute goal on project canyon-server: Could not resolve dependencies for project com.canyonmodded:canyon-server:jar:1.7.3: Failed to collect dependencies at org.bukkit:minecraft-server:jar:1.7.3: Failed to read artifact descriptor for org.bukkit:minecraft-server:jar:1.7.3: Could not transfer artifact org.bukkit:minecraft-server:pom:1.7.3 from/to bukkit-repo (https://repo.canyonmodded.com): Transfer failed for https://repo.canyonmodded.com/org/bukkit/minecraft-server/1.7.3/minecraft-server-1.7.3.pom 521 Origin Down -> [Help 1]```

**Comment by anna548** [comment]
having same issue

**Comment by patapancakes** [comment]
Same problem!

**Comment by KoboDev** [comment]
Fixed, replaced the bukkit-repo with a live link.

**Comment by Moresteck** [comment]
> Fixed, replaced the bukkit-repo with a live link.

That didn't fix the issue – the following error occurs for every bukkit-repo dependency:
`
[WARNING] Could not validate integrity of download from https://download938.mediafire.com/jzs3lz3gm1jg/xuiz2lwjyfiljfp/minecraft-server.jar/org/bukkit/minecraft-server/1.7.3/minecraft-server-1.7.3.pom: Checksum validation failed, expected <!DOCTYPE but is 939baf22813842948029d9f9b259195d0314360a
`

Fresh install, following the steps from README.md.
I assume it's because the mediafire download link expired.
Perhaps we shouldn't use mediafire as a static location file hosting?

**Comment by KoboDev** [comment]
> > Fixed, replaced the bukkit-repo with a live link.
> 
> That didn't fix the issue – the following error occurs for every bukkit-repo dependency:
> `[WARNING] Could not validate integrity of download from https://download938.mediafire.com/jzs3lz3gm1jg/xuiz2lwjyfiljfp/minecraft-server.jar/org/bukkit/minecraft-server/1.7.3/minecraft-server-1.7.3.pom: Checksum validation failed, expected <!DOCTYPE but is 939baf22813842948029d9f9b259195d0314360a`
> 
> Fresh install, following the steps from README.md.
> I assume it's because the mediafire download link expired.
> Perhaps we shouldn't use mediafire as a static location file hosting?

Replying for github only users, this has been fixed with a permanent link.
